name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Build
        run: flutter build web --base-href "/treehole/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
